### PR TITLE
[Team 5 Agent] Final version hopefully

### PR DESCRIPTION
**Pull request by anhnguyen24**
Our team has been proof-reading it for the whole night so hopefully there is no silly mistakes.

### CODE REVIEW

**Review by NGovani — APPROVED** [review]
Pages looks good

**Comment by ezgimez** [comment]
lgtm (BUT i honeslty kinda skimmed it., and NOT read it ;) .)

**Comment by ezgimez** [comment]
let's merrrggeeeeee peoppplleeeeeee

**Comment by anhnguyen24** [comment]
Please merge for me boss I have no power here 😩

**Comment by ezgimez** [comment]
as I said, Disclaimer: _I'm not responsible for the grammar/style  mistakes in this merge_

**Pull request merged**
