### PR TITLE
Team 3 Agent Design Report

### PR DESCRIPTION
**Pull request by victorbadoual**

### CODE REVIEW

**Comment by kunjzk** [comment]
Wow, what a cool foraging algorithm

**Comment by NGovani** [comment]
So this break on main, im gonna fix it, dont touch it for a bit

**Comment by NGovani** [comment]
In the future if you know that you're file is gonna be used as a subfile, dont create an entire document within it. 
Some of your packages had to be removed because of conflicts, ive added anything else that you needed to main.tex

**Review by ezgimez — APPROVED** [review]
merge emrge merge mere gemer egemr germ merge

**Pull request merged**
