### PR TITLE
Init PR test

### PR DESCRIPTION
**Pull request by Spruudis**
Future work will be done on a fork cause otherwise the notifications will drive me mad

### CODE REVIEW

**Comment by ezgimez** [comment]
is this fork for Team4 agent specs?

**Comment by ezgimez** [comment]
can we not modify the notifications lol

**Comment by yp717** [comment]
you can set up an email rule to just dump them all in a folder (10/10 would recommend)

**Review by ezgimez — APPROVED** [review]
good spelling for the name, I guess

**Comment by ezgimez** [comment]
yeah I created a filter and a label in gmail -- seems to be working, just like @yp717 said.
@Spruudis

**Pull request merged**
